<a href="https://colab.research.google.com/github/Diksha-Bora/Machine_Learning/blob/main/KMeans29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

In [18]:
from sklearn.datasets import load_iris
iris = load_iris()
data = pd.DataFrame(iris.data, columns = iris.feature_names)
data["target"] = iris.target
data.columns = data.columns.str.capitalize()
data.head()

Sepal length (cm)  Sepal width (cm)  Petal length (cm)  Petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0

In [19]:
data["Target"].unique()

array([0, 1, 2])

In [20]:
x = data.drop("Target",axis=1)
y = data["Target"]

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

In [22]:
from sklearn.cluster import KMeans
km = KMeans(n_clusters=2)
km.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=2)

In [23]:
y_pred_train = km.predict(x_train)
y_pred_test = km.predict(x_test)

In [24]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("TRAIN")
print("The accuracy_score is : \n",accuracy_score(y_train,y_pred_train))
print("The confusion_matrix is : \n",confusion_matrix(y_train,y_pred_train))
print("TEST")
print("The accuracy_score is : \n",accuracy_score(y_test,y_pred_test))
print("The confusion_matrix is : \n",confusion_matrix(y_test,y_pred_test))

TRAIN
The accuracy_score is : 
 0.008333333333333333
The confusion_matrix is : 
 [[ 0 40  0]
 [39  1  0]
 [40  0  0]]
TEST
The accuracy_score is : 
 0.06666666666666667
The confusion_matrix is : 
 [[ 0 10  0]
 [ 8  2  0]
 [10  0  0]]
