<a href="https://colab.research.google.com/github/Diksha-Bora/Machine_Learning/blob/main/StackingClassifier32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [32]:
from sklearn.datasets import load_wine
wine = load_wine()
data = pd.DataFrame(wine.data, columns = wine.feature_names)
data["target"] = wine.target
data.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [33]:
data["target"].unique()

array([0, 1, 2])

In [34]:
x = data.drop("target",axis=1)
y = data["target"]

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state = 42,stratify =y)

In [36]:
from sklearn.tree import DecisionTreeClassifier
clsf1 = DecisionTreeClassifier()
from sklearn.ensemble import RandomForestClassifier
clsf2 = RandomForestClassifier()
from sklearn.naive_bayes import MultinomialNB
clsf3 = MultinomialNB()
from sklearn.neighbors import KNeighborsClassifier
clsf4 = KNeighborsClassifier()

In [37]:
from sklearn.ensemble import StackingClassifier
stc = StackingClassifier(estimators=[("dtc",clsf1),("rfc",clsf2),("mnb",clsf3),("knc",clsf4)],
                         final_estimator= clsf2,
                         verbose = True,
                         n_jobs=-1)
stc.fit(x_train,y_train)

StackingClassifier(estimators=[('dtc', DecisionTreeClassifier()),
                               ('rfc', RandomForestClassifier()),
                               ('mnb', MultinomialNB()),
                               ('knc', KNeighborsClassifier())],
                   final_estimator=RandomForestClassifier(), n_jobs=-1,
                   verbose=True)

In [38]:
y_pred_train = stc.predict(x_train)
y_pred_test = stc.predict(x_test)

In [39]:
from sklearn.metrics import classification_report, confusion_matrix
print("TRAIN")
print("classification_report is : \n",classification_report(y_train,y_pred_train))
print("confusion_matrix is : \n",confusion_matrix(y_train,y_pred_train))
print("TEST")
print("classification_report is : \n",classification_report(y_test,y_pred_test))
print("confusion_matrix is : \n",confusion_matrix(y_test,y_pred_test))

TRAIN
classification_report is : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        41
           1       1.00      1.00      1.00        50
           2       1.00      1.00      1.00        33

    accuracy                           1.00       124
   macro avg       1.00      1.00      1.00       124
weighted avg       1.00      1.00      1.00       124

confusion_matrix is : 
 [[41  0  0]
 [ 0 50  0]
 [ 0  0 33]]
TEST
classification_report is : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00        15

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54

confusion_matrix is : 
 [[18  0  0]
 [ 0 21  0]
 [ 0  0 15]]
